services:
  db:
    image: postgres:15
    container_name: ucsal_db
    environment:
      - POSTGRES_DB=avaliacao_db
      - POSTGRES_USER=user_ucsal
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"